/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.login.controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Eduardo
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTextoCadastroCliente = new javax.swing.JLabel();
        labelIdAtendente = new javax.swing.JLabel();
        campoIdAtendente = new javax.swing.JTextField();
        labelNomeAtendente = new javax.swing.JLabel();
        campoNomeAtendente = new javax.swing.JTextField();
        labelCadastroUsuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        campoCadastroSenha = new javax.swing.JPasswordField();
        labelConfirmarSenha = new javax.swing.JLabel();
        campoConfirmacaoSenha = new javax.swing.JPasswordField();
        botaoSalvarNovoAtendente = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoLimparCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        labelTextoCadastroCliente.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        labelTextoCadastroCliente.setText("Cadastro de Atendente");
        labelTextoCadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelTextoCadastroCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelIdAtendente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelIdAtendente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIdAtendente.setText("Id do Atendente");

        campoIdAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdAtendenteActionPerformed(evt);
            }
        });

        labelNomeAtendente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNomeAtendente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNomeAtendente.setText("Nome do Atendente");

        campoNomeAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeAtendenteActionPerformed(evt);
            }
        });

        labelCadastroUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCadastroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCadastroUsuario.setText("Usuário");

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        labelSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSenha.setText("Senha");

        labelConfirmarSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelConfirmarSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelConfirmarSenha.setText("Confirmar Senha");

        botaoSalvarNovoAtendente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSalvarNovoAtendente.setText("Cadastrar");
        botaoSalvarNovoAtendente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSalvarNovoAtendente.setMaximumSize(new java.awt.Dimension(105, 92));
        botaoSalvarNovoAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarNovoAtendenteActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
        });
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoLimparCampos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoLimparCampos.setText("Limpar");
        botaoLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoLimparCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparCamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(botaoSalvarNovoAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(botaoLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTextoCadastroCliente)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdAtendente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoIdAtendente)
                        .addComponent(campoNomeAtendente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoCadastroSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoConfirmacaoSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelConfirmarSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelNomeAtendente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTextoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelIdAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoIdAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCadastroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelConfirmarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoConfirmacaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarNovoAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void botaoSalvarNovoAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarNovoAtendenteActionPerformed
        if (campoIdAtendente.getText().matches("") || campoNomeAtendente.getText().matches("")  
                || campoUsuario.getText().matches("") || campoCadastroSenha.getText().matches("")
                || campoConfirmacaoSenha.getText().matches("")) {
            JOptionPane.showMessageDialog(rootPane, "É necessário preencher todos os campos!", 
                    "Pequi Crédito", JOptionPane.WARNING_MESSAGE);
        } else {
        LoginController cadastro = new LoginController();
        cadastro.cadastroUsuario(this);
        }
    }//GEN-LAST:event_botaoSalvarNovoAtendenteActionPerformed

    private void campoNomeAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeAtendenteActionPerformed

    private void campoIdAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdAtendenteActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
       
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
       this.dispose();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    private void botaoLimparCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparCamposMouseClicked
       campoIdAtendente.setText("");
       campoNomeAtendente.setText("");
       campoUsuario.setText("");
       campoCadastroSenha.setText("");
       campoConfirmacaoSenha.setText("");
    }//GEN-LAST:event_botaoLimparCamposMouseClicked

    public JPasswordField getCampoCadastroSenha() {
        return campoCadastroSenha;
    }

    public void setCampoCadastroSenha(JPasswordField campoCadastroSenha) {
        this.campoCadastroSenha = campoCadastroSenha;
    }

    public JPasswordField getCampoConfirmacaoSenha() {
        return campoConfirmacaoSenha;
    }

    public void setCampoConfirmacaoSenha(JPasswordField campoConfirmacaoSenha) {
        this.campoConfirmacaoSenha = campoConfirmacaoSenha;
    }

    public JTextField getCampoIdAtendente() {
        return campoIdAtendente;
    }

    public void setCampoIdAtendente(JTextField campoIdAtendente) {
        this.campoIdAtendente = campoIdAtendente;
    }

    public JTextField getCampoNomeAtendente() {
        return campoNomeAtendente;
    }

    public void setCampoNomeAtendente(JTextField campoNomeAtendente) {
        this.campoNomeAtendente = campoNomeAtendente;
    }

    public JTextField getCampoUsuario() {
        return campoUsuario;
    }

    public void setCampoUsuario(JTextField campoUsuario) {
        this.campoUsuario = campoUsuario;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimparCampos;
    private javax.swing.JButton botaoSalvarNovoAtendente;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPasswordField campoCadastroSenha;
    private javax.swing.JPasswordField campoConfirmacaoSenha;
    private javax.swing.JTextField campoIdAtendente;
    private javax.swing.JTextField campoNomeAtendente;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel labelCadastroUsuario;
    private javax.swing.JLabel labelConfirmarSenha;
    private javax.swing.JLabel labelIdAtendente;
    private javax.swing.JLabel labelNomeAtendente;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTextoCadastroCliente;
    // End of variables declaration//GEN-END:variables
}
